image: python:3.8-slim-buster

stages:
  - code-quality-test
  - unit-integration-test
  - end2end-test
  - docker-build-test

before_script:
  - apt-get update
  - apt install -y build-essential
  - apt install -y build-essential
  - apt install -y libgl1-mesa-glx
  - apt install -y libglib2.0-0
  - apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6

  - pip install --upgrade pip
  - pip install -r requirements.txt

code-quality:
  stage: code-quality-test
  tags:
    - code
  script:
    - pylint app/ tests/ app.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - app/**/*
        - tests/**/*
        - app.py

unit:
  stage: unit-integration-test
  tags:
    - code
  script:
    - pytest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - app/**/*
        - tests/**/*

end2end:
  stage: end2end-test
  tags:
    - code
  script:
    - python app.py --env local --test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - app/**/*
        - tests/**/*
        - app.py

docker-build:
  stage: docker-build-test
  image: docker:24.0.5
  tags:
    - docker
  services:
    - docker:24.0.5-dind
  script:
    - docker build --tag $CI_PROJECT_NAME:latest .
  before_script:
    - []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - app/**/*
        - tests/**/*
        - app.py
        - Dockerfile
